//<!-- core -->
$LAB.script('js/jquery.min.js').wait()
    .script('js/jquery-ui.min.js').wait()
	.script('js/bootstrap.min.js').wait()
	.script('js/angular.min.js').wait()
    .script('js/angular-locale_pt-br.js').wait()
    .script('js/angular-route.min.js').wait()
	.script('js/angular-resource.min.js').wait()
	.script('js/angular-animate.min.js').wait()
    .script('js/angular-sanitize.min.js').wait()
	//<!-- libs -->
    .script('js/jquery.inputmask.min.js').wait()
	.script('js/fancybox/jquery.fancybox.pack.js').wait()
	.script('js/jquery.inputmask.regex.extensions.min.js').wait()
	.script('js/toaster.min.js').wait()
	.script('js/ui-bootstrap-tpls.min.js').wait()
	.script('js/jquery.data-tables.min.js').wait()
    .script('js/data-tables.bootstrap.min.js').wait()
    .script('js/chosen.min.js').wait()
    .script('js/masks.min.js').wait()
    .script('js/select2.min.js').wait()
	.script('js/bootstrap-datepicker.min.js').wait()
	.script('js/angular-bootstrap-lightbox.min.js').wait()
	.script('js/jquery.jcarousel.min.js').wait()
	.script('js/jcarousel.responsive.min.js').wait()
	.script('js/angular-file-upload2.min.js').wait()	
	//<!-- aplicacao -->
    .script('app-config/extension.js').wait()
	.script('app-config/customFilters.js').wait()
	.script('app-config/rotas.js').wait()
    .script('app-config/httpInterceptor.js').wait()
	.script('app-config/api.js').wait()
	.script('app-config/app.js').wait()
	.script('app-config/menu.js').wait();
